### ISSUE TITLE
 RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by marcolino** [gleero/grunt-favicons#36]
When running `grunt favicons` I get a bunch of these warnings:

    (node) warning: Recursive process.nextTick detected. This will break in the next version of node. Please use setImmediate for recursive deferral.

And, most important, this fatal error:

    util.js:35
      var str = String(f).replace(formatRegExp, function(x) {
                          ^
    RangeError: Maximum call stack size exceeded

This is the relevant part of my Gruntfile.js:

    ...
    
    favicons: {
      options: {
      },
      icons: {
        src: 'logo.png',
        dest: 'dist/images/icons'
      }
    }
    
    ...
    
    grunt.loadNpmTasks('grunt-favicons');

    grunt.registerTask('favicons', [
      'favicons',
    ]);

I'm using:
 - OS: Centos 6.5
 - npm: 1.3.21
 - grunt. 0.4.5
 - grunt-favicons: 0.6.4
 - ImageMagick.x86_64: 6.5.4.7-6.el6_2

This is the image "logo.png": https://www.dropbox.com/s/69tuf34mrvlz9yo/logo.png

What am I missing?

**Comment by kossmann** [comment]
@gclapperton I've had the same problem, thanks!!!

**Comment by ckollars** [comment]
Ran into the same issue and this was a great help. Thanks!
