### ISSUE TITLE
possible execSync problem rendering grunt-favicons unusable

### ISSUE THREAD

**Issue by marten-seemann** [gleero/grunt-favicons#52]
Installing this module via 

    npm install grunt-favicons

fails because of 

    > execSync@1.0.2 install /[...path...]/node_modules/execSync
    > node install.js

    [execsync v1.0.2] Attempting to compile native extensions.
    [execSync v1.0.2]
       Native code compile failed!!

Running
 
    grunt favicons

then fails with

    Loading "favicons.js" tasks...ERROR
      >> Error: Cannot find module './build/Release/shell'

My system configuration:
* npm version: 2.5.1
* node version: v0.12.0

**Comment by vvelar** [comment]
Is it possible to use native node.js execSync instead of broken package ?

http://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options

**Comment by marten-seemann** [comment]
Maybe. You could try to do this.
I already fixed the bug and created a PR (#53) using another package and it works just fine.
