### ISSUE TITLE
Grunt Tasks not progressing

### ISSUE THREAD

**Issue by robertlawson86** [gleero/grunt-favicons#61]
Hi I have installed both the Grunt Module and ImageMagick( I know this is installed as the image convert method is working) however the Grunt task gets stuck at Running "favicons:icons" and never seems to progress, anyone got any ideas or had similar issues? My set up for the task is:
`favicons: {
			icons: {
				src: 'logo.png',
				dest: '<%= destPath %>logos'
			}
		}`

Any help appreciated

Robert

**Comment by konstantin24121** [comment]
I have a same problem

**Comment by konstantin24121** [comment]
stops after           
> 51  return exec(cmd);

command exec do not anything. What problem with sync-exec?

**Comment by aproskam** [comment]
Hi,

Same problem here.
Keeps hanging on "Resizing images for "path/name"..."

I'm trying it on a Windows 8.1 machine, I also tried to use the grunt-favicons-windows package

**Comment by rhhamburg** [comment]
I had the same problem. After updating `sync-exec` from version `0.4.0` to `0.6.0` in the package.json file it works now.

**Comment by aproskam** [comment]
@rhhamburg thanks mate, that worked for me as well!

**Comment by konstantin24121** [comment]
@rhhamburg thank you! work's great!
